#!/bin/bash

size() {
    # print the file size in bytes
    stat -c %s "$1"
}

prev=$(ls *.csv | tail -1)
yyyymmdd=$(date +%F)
new=${yyyymmdd}-$(date +%H-%M-%S).csv
wget --quiet --compression=auto -O "$new" https://www.arcgis.com/sharing/rest/content/items/4cc62b3a510949c7a8167f6baa3e069d/data
if [ $(size "$new") -lt 10000 ]; then
    echo "Too short (content being updated?)"
    rm "$new"
    exit 1
fi
if [ $(size "$prev") -eq $(size "$new") ]; then
    echo "No new CSV"
    rm "$new"
    exit 1
fi
echo "Found new CSV"
deaths=$(./count_deaths "$new") || exit 1
line="$yyyymmdd,Florida,$deaths"
echo "Appending $line to fl_resident_deaths.csv"
echo "$line" >>../data_deaths/fl_resident_deaths.csv
